apiVersion: apps/v1
kind: Deployment
metadata:
  name: video
spec:
  selector:
    matchLabels:
      app: video
  replicas: 1
  template:
    metadata:
      labels:
        app: video
    spec:
      containers:
        - name: video
          image: registry.cn-hangzhou.aliyuncs.com/uat2/spring:latest
          ports:
            - containerPort: 8080