apiVersion: apps/v1
kind: Deployment
metadata:
  name: video
spec:
  selector:
    matchLabels:
      app: video
  replicas: 1
  template:
    metadata:
      labels:
        app: video
    spec:
      containers:
        - name: okteto
          image: video:latest
          ports:
            - containerPort: 8080